name: project_craftoria
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  animations: ^2.1.0
  cupertino_icons: ^1.0.6
  dio: ^5.9.0
  curved_navigation_bar: ^1.0.6
  shared_preferences: ^2.5.3
  http: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Arimo
      fonts:
        - asset: assets\fonts\Arimo-Regular.ttf

  assets:
    - assets/images/

    
